  apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "whereami-backend-2-grpc"
    annotations:
      cloud.google.com/neg: '{"exposed_ports":{"9090":{}}}'
  spec:
    ports:
    - port: 9090
      protocol: TCP
      name: grpc
      targetPort: 9090
    selector:
      app: "whereami-backend-2-grpc"